name: netmasha
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  another_flutter_splash_screen: ^1.2.0
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  floating_navbar: ^2.0.2
  floating_navigation_bar: ^0.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_custom_carousel_slider: ^1.2.0
  flutter_localizations:
    sdk: flutter
  http: ^1.1.2
  molten_navigationbar_flutter: ^1.0.1
  phosphor_flutter: ^2.0.1
  shared_preferences: ^2.2.2
  translucent_navigation_bar: ^1.0.0
flutter_bloc: ^8.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
  fonts:
   - family: IBM Plex Sans Arabic
     fonts:
        - asset: fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
        - asset: fonts/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200
        - asset: fonts/IBMPlexSansArabic-Light.ttf 
          weight: 300
        - asset: fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: fonts/IBMPlexSansArabic-Thin.ttf
          weight: 100


